### ISSUE TITLE
TypeError: Cannot read property 'translations' of undefined

### ISSUE THREAD

**Issue by krupalagravat** [danialkalbasi/react-native-power-translator#12]
Only getting warning when sending wrong language code .
 
TranslatorFactory.createTranslator()
            .translate(MainLanguages[currentKey], langCode)
            .then(translated => {})

> Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'translations' of undefined

**Comment by gautamr2** [comment]
@#1danialkalbasi can you please help on this, I am facing same issue.

**Comment by waqaramjad** [comment]
facing same issue

**Comment by ajaykumar97** [comment]
I was also facing the same issue. Try replacing the Google API key for translation provided in the example project with your own Google API key with the Google Translate API enabled.

**Comment by Imki123** [comment]
I solved that issue. 
1. Go https://cloud.google.com/translate/docs/basic/setup-basic
2. Make a new Project
3. Go https://console.cloud.google.com/apis/credentials
4. Make a new API KEY
5. Copy API KEY and Use that key
