### ISSUE TITLE
can't use!

### ISSUE THREAD

**Issue by Jianghaowen** [danialkalbasi/react-native-power-translator#15]
`[Unhandled promise rejection: Error: The URL: https://api.microsofttranslator.com/V2/Http.svc/Translate?&to=fr&text='Engineering physics or engineering science refers to the study of the combined disciplines of physics', Error: Error: The URL: https://api.microsofttranslator.com/V2/Http.svc/Translate?&to=fr&text='Engineering physics or engineering science refers to the study of the combined disciplines of physics', Error: Error: The URL: https://api.microsofttranslator.com/V2/Http.svc/Translate?&to=fr&text='Engineering physics or engineering science refers to the study of the combined disciplines of physics', Error: Generic error]`

upon is my test error message.

**Comment by danialkalbasi** [comment]
Please follow up on this issue instead https://github.com/danialkalbasi/react-native-power-translator/issues/18.
