### ISSUE TITLE
TypeError: Cannot read property 'translations' of undefined

### ISSUE THREAD

**Issue by Arslan24** [danialkalbasi/react-native-power-translator#18]
I am implementing this (react-native-power-translator) but i am getting this error. 

TypeError: Cannot read property 'translations' of undefined

- I even enable the translation Api in the Google Cloud.

**Here is MY Code

import React, { Component } from 'react';
import { PowerTranslator , ProviderTypes, TranslatorConfiguration, TranslatorFactory   } from 'react-native-power-translator';
import { View, ScrollView, TouchableOpacity, Text } from 'react-native';

export default class PowerTranslatorDemo extends Component {

    constructor(props) {
        super(props);
        console.log('props are ', props);
        this.state = { languageCode: 'fi' };
    }

    
    render() {
        const styles = this.getStyles();
        TranslatorConfiguration.setConfig(ProviderTypes.Google, 'GoogleApiKey', this.state.languageCode);
        
        return (
            <ScrollView style={styles.container}>
                <View style={styles.languageBar}>
                    <TouchableOpacity onPress={() => { this.changeLanguage('en') }}><Text style={styles.p}>English</Text></TouchableOpacity>
                    <TouchableOpacity onPress={() => { this.changeLanguage('fr') }}><Text style={styles.p}>French</Text></TouchableOpacity>
                    <TouchableOpacity onPress={() => { this.changeLanguage('ru') }}><Text style={styles.p}>Russian</Text></TouchableOpacity>
                    <TouchableOpacity onPress={() => { this.changeLanguage('de') }}><Text style={styles.p}>German</Text></TouchableOpacity>
                </View>
                 <View>
                    <PowerTranslator  text={'A Confucian Revival Began'} />
                    <PowerTranslator  text={'Author: Confucianism'} />
                </View>

                <View style={styles.section}>
                    <PowerTranslator style={styles.p} text={'Confucianism was particularly strong during the Han Dynasty, whose greatest thinker was Dong Zhongshu, who integrated Confucianism with the thoughts of the Zhongshu School and the theory of the Five Elements. He also was a promoter of the New Text school, which considered Confucius as a divine figure and a spiritual ruler of China, who foresaw and started the evolution of the world towards the Universal Peace.'} />
                </View>

                <View style={styles.section}>
                    <PowerTranslator style={styles.p} text={'Confucianism was particularly strong during the Han Dynasty, whose greatest thinker was Dong Zhongshu, who integrated Confucianism with the thoughts of the Zhongshu School and the theory of the Five Elements. He also was a promoter of the New Text school, which considered Confucius as a divine figure and a spiritual ruler of China, who foresaw and started the evolution of the world towards the Universal Peace.'} />
                </View>

                <View style={styles.section}>
                    <PowerTranslator style={styles.p} text={'Engineering physics or engineering science refers to the study of the combined disciplines of physics'} />
                </View>
            </ScrollView>
        );
    }

    getStyles() {
        return {
            container: {
                padding: 40,
                backgroundColor: '#FAFAFA',
            },
            section: {
                marginTop: 15,
                marginBottom: 15,
            },
            title: {
                marginTop: 80,
                marginBottom: 5,
                fontWeight: 'bold',
                fontSize: 38,
                lineHeight: 38
            },
            subtitle: {
                color: '#B3B3B3',
            },
            p: {
                color: '#828280',
                lineHeight: 24
            },
            languageBar: {
                flexDirection: 'row',
                justifyContent: 'space-between'
            },
            languageBarItem: {
                color: '#828280',
            }
        }
    }

    changeLanguage(languageCode) {
        this.setState({ languageCode: languageCode });
    }
}

Help would be appreciated.**

**Comment by Arslan24** [comment]
cc @danialkalbasi @haowei99

**Comment by carlosbbraga** [comment]
I´m having the same issue!

**Comment by danialkalbasi** [comment]
I'm planning to deprecate this package soon as I can't see much value while Google builds an official package for translation https://www.npmjs.com/package/@google-cloud/translate. Previously I wanted to decouple the JS from React Native and provide RN component with JS library, but it seems with the package from Google, you should be able to do a similar thing.

**Comment by Arslan24** [comment]
@danialkalbasi thanks for a reply and  @carlosbbraga you can achieve the translated text by using this method. i achieve it by doing that. and you make sure to enable the **Cloud translation api** in google cloud platform before sending a request.

const TranslateText = ( {value , lang_code , fromLang } ) => {

  if (lang_code == undefined){
    lang_code = 'en';
  }
  console.log('language is ', lang_code)
  **let fromLang = fromLang ; // You can also write in a string format in any language **'en'** 
  let toLang = lang_code;   // Same you can do here. as i getting the values from another component.
  let text = value;
  console.log('value of textblock is ' , text)
  const API_KEY = 'YOUR API KEY';
  const [transTxt , settext] = React.useState(''); 

  let url = `https://translation.googleapis.com/language/translate/v2?key=${API_KEY}`;
  url += '&q=' + encodeURI(text);
  url += `&source=${fromLang}`;
  url += `&target=${toLang}`;

  console.log ('url is ' , url);
  fetch(url, { 
    method: 'GET',
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json"
    }
  })
  .then(res => res.json())
  .then((response) => {
    console.log("response from google: ", response);
    console.log("response from google again: ", response.data.translations[0].translatedText);
    transTxt = response.data.translations[0].translatedText;
    settext(response.data.translations[0].translatedText);
    console.log ('data from the response', transTxt)
   })
   
  .catch(error => {
    console.log("There was an error with the translation request: ", error);
  });
  return <Text> {transTxt} </Text>; 
}**

**Comment by radekzz** [comment]
I faces the same error and it appears that i was passing wrong[ language string](https://cloud.google.com/translate/docs/languages) into setConfig.

Example for czech language:

```
TranslatorConfiguration.setConfig(
    ProviderTypes.Google,
    googleTranslateApi,
    lang.lang === 'cz' ? 'cs' : lang.lang,
  );
```

Thanks @danialkalbasi to NOT deprecated this library as Google's library sucks.
