### ISSUE TITLE
Default value

### ISSUE THREAD

**Issue by waltershub** [danialkalbasi/react-native-power-translator#6]
I think it would be great if there was an optional  default prop that allows the text to be set to the original text prop in case of no internet or if there is something wrong with the api creds.

**Comment by waltershub** [comment]
@danialkalbasi I made the pull request to have the text default to the original text, my linter reformatted the  a lot of the file, but all I changed was setting the original state to props.text, can't see how this would hurt anyone and would help with anyone who has a slow internet connection

**Comment by danialkalbasi** [comment]
@waltershub thanks for the PR. There are some issues I commented which need to be fixed before it merges into master. Let me if you need help!
